apiVersion: v1
kind: Secret
metadata:
  name: ${CLUSTER_NAME}-talos-ca
  namespace: $NAMESPACE
type: Opaque
data:
  # Talos Machine CA Certificate (base64 from talosctl gen config)
  # Copy from controlplane.yaml -> machine.ca.crt
  tls.crt: ""
  # Talos Machine CA Private Key (base64 from talosctl gen config)
  # Copy from controlplane.yaml -> machine.ca.key
  tls.key: ""
  # Talos bootstrap token (from worker config -> cluster.token)
  # Example: u1auey.78f6fcj1pzoaur2i
  token: ""