apiVersion: v1
kind: Secret
metadata:
  name: talos-machine-ca
  namespace: default
type: Opaque
data:
  # Talos Machine CA Certificate (base64 from talosctl gen config)
  # Copy from controlplane.yaml -> machine.ca.crt
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQakNCOGFBREFnRUNBaEEwSWNzakxrWC9zV1ZCdW1wRW9xditNQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5URXdNamd3T0RRNE1UZGFGdzB6TlRFd01qWXdPRFE0TVRkYU1CQXhEakFNQmdOVgpCQW9UQlhSaGJHOXpNQ293QlFZREsyVndBeUVBL2huekd4d1BOaUdPNFhnNFkrUWV4ZC8wb29wSStCMkpaenpmCmtIOHY4dStqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVa0pxK3Jhb1F1elA1RThOKwpaWFRTWDlpQzZXUXdCUVlESzJWd0EwRUFpV01CZnBBVlIxMTQyTXdVd08zZDBTQ2ZTR3ZIamw5TEtDWTBTM3hLCjlMMWRCWFI1TDdFY1NWUnZJUGxVbkN4dUx6Y2VmcjlUTGx2SkxNOVF5cWt1QkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==

  # Talos Machine CA Private Key (base64 from talosctl gen config)
  # Copy from controlplane.yaml -> machine.ca.key
  ca.key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJSXFidDBCbGpEb0cyc3RNRTN1TXMzQVpRRXRXbUdOa3NrZTEwOFF0c29NcAotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K

  # Talos bootstrap token (from worker config -> cluster.token)
  # Example: u1auey.78f6fcj1pzoaur2i
  token: dTFhdWV5Ljc4ZjZmY2oxcHpvYXVyMmk=
