apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${CLUSTER_NAME}-talos-tls-cert
  namespace: $NAMESPACE
spec:
  secretName: ${CLUSTER_NAME}-talos-tls-cert
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days before
  isCA: false
  privateKey:
    algorithm: Ed25519
    size: 256
  usages:
    - digital signature
    - key encipherment
    - server auth
  ipAddresses:
    - 127.0.0.1
    # Add your custom IPs here
  issuerRef:
    name: ${CLUSTER_NAME}-talos-ca  # 01-issuer.yaml
    kind: Issuer
    group: cert-manager.io
